
import { Card, CardContent } from "@/components/ui/card";

interface DisclaimerCardProps {
  analysisDate?: string | Date | null;
}

const DisclaimerCard = ({ analysisDate }: DisclaimerCardProps) => {
  // Format the analysis date or fall back to current date
  const formatDate = () => {
    if (analysisDate) {
      try {
        const date = typeof analysisDate === "string" ? new Date(analysisDate) : analysisDate;
        return date.toLocaleDateString();
      } catch {
        return new Date().toLocaleDateString();
      }
    }
    return new Date().toLocaleDateString();
  };

  return (
    <Card className="shadow-lg border-0 bg-slate-100/80 backdrop-blur-sm w-full">
      <CardContent className="text-center py-4 md:py-6 px-4 md:px-6">
        <p className="text-xs md:text-sm font-semibold text-slate-800 mb-2 md:mb-3">
          AI-GENERATED RESEARCH ONLY
        </p>
        <p className="text-xs md:text-sm text-slate-700 mb-2 md:mb-3 leading-relaxed">
          The trade setups, entry/exit levels, and strategies shown here are{" "}
          <strong>AI-generated hypothetical analyses based on historical data</strong>. They are not
          investment advice, not recommendations to buy or sell any securities, and may be wrong
          or incomplete. You remain fully responsible for all trading decisions and risk.
        </p>
        <p className="text-xs text-slate-500 mt-3 md:mt-4 pt-3 md:pt-4 border-t border-slate-300">
          Generated by StockAnalyzer Pro | {formatDate()}
        </p>
      </CardContent>
    </Card>
  );
};

export default DisclaimerCard;
