
import { Card, CardContent } from "@/components/ui/card";

const DisclaimerCard = () => {
  return (
    <Card className="mt-8 shadow-lg border-0 bg-slate-100/80 backdrop-blur-sm">
      <CardContent className="text-center py-6">
        <p className="text-sm text-slate-600 mb-2">
          Generated by StockAnalyzer Pro | {new Date().toLocaleDateString()}
        </p>
        <p className="text-xs text-slate-500">
          This report is for informational purposes only and should not be considered financial advice.
          Always conduct your own research before making investment decisions.
        </p>
      </CardContent>
    </Card>
  );
};

export default DisclaimerCard;
