import { Link } from "react-router-dom";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import Header from "@/components/Header";
import { ArrowLeft } from "lucide-react";
import { Button } from "@/components/ui/button";

const Disclaimer = () => {
  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 via-blue-50 to-indigo-50">
      <Header />
      <div className="h-16" />
      <div className="container mx-auto px-4 py-8 max-w-4xl">
        <div className="mb-6">
          <Link to="/">
            <Button variant="ghost" className="mb-4">
              <ArrowLeft className="h-4 w-4 mr-2" />
              Back to Home
            </Button>
          </Link>
        </div>

        <Card className="shadow-xl border-0 bg-white/90 backdrop-blur-sm">
          <CardHeader>
            <CardTitle className="text-3xl font-bold text-slate-800">
              Disclaimer & Terms of Use
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-6 text-slate-700">
            <section>
              <h2 className="text-xl font-semibold text-slate-800 mb-3">1. AI-Generated Content</h2>
              <p className="text-sm leading-relaxed">
                All analysis, strategies, trade setups, entry/exit levels, and recommendations
                displayed on StockAnalyzer Pro are generated by artificial intelligence algorithms
                based on historical market data. These outputs are:
              </p>
              <ul className="list-disc list-inside mt-2 space-y-1 text-sm ml-4">
                <li>Hypothetical and for research purposes only</li>
                <li>May be inaccurate, incomplete, or delayed</li>
                <li>Not personalized financial advice</li>
                <li>Not guaranteed to be correct or profitable</li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-slate-800 mb-3">
                2. Not SEBI-Registered Investment Advice
              </h2>
              <p className="text-sm leading-relaxed">
                StockAnalyzer Pro is <strong>not</strong> registered with the Securities and
                Exchange Board of India (SEBI) as:
              </p>
              <ul className="list-disc list-inside mt-2 space-y-1 text-sm ml-4">
                <li>An Investment Adviser</li>
                <li>A Research Analyst</li>
                <li>An Investment Advisor</li>
              </ul>
              <p className="text-sm leading-relaxed mt-3">
                Nothing on this platform constitutes personalized financial advice or a
                buy/sell/hold recommendation for any specific security.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-slate-800 mb-3">
                3. Platform Purpose and Limitations
              </h2>
              <p className="text-sm leading-relaxed">
                StockAnalyzer Pro is a prototype AI-driven technical research tool made available
                in a private beta. The platform:
              </p>
              <ul className="list-disc list-inside mt-2 space-y-1 text-sm ml-4">
                <li>Is intended for evaluation and feedback purposes only</li>
                <li>Does not provide personalized financial advice</li>
                <li>Does not manage client funds</li>
                <li>Should not be treated as a tips or signal service</li>
                <li>Is provided on an &apos;as is&apos; basis with no warranties</li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-slate-800 mb-3">4. User Responsibility</h2>
              <p className="text-sm leading-relaxed">
                By using StockAnalyzer Pro, you acknowledge and agree that:
              </p>
              <ul className="list-disc list-inside mt-2 space-y-1 text-sm ml-4">
                <li>
                  You are solely responsible for your investment and trading decisions
                </li>
                <li>
                  You should consult a SEBI-registered adviser before acting on any information
                  from this platform
                </li>
                <li>
                  You will not treat any analysis, entry/exit level, or strategy as a direct
                  instruction to trade
                </li>
                <li>
                  You will not publicly redistribute or market the platform&apos;s trade ideas as
                  investment advice or tips
                </li>
                <li>
                  Past performance, backtests, or simulated results do <strong>not</strong>{" "}
                  guarantee future returns
                </li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-slate-800 mb-3">5. No Guarantees</h2>
              <p className="text-sm leading-relaxed">
                StockAnalyzer Pro and its creators:
              </p>
              <ul className="list-disc list-inside mt-2 space-y-1 text-sm ml-4">
                <li>Make no guarantees about the accuracy, completeness, or timeliness of any analysis</li>
                <li>Are not responsible for any profits or losses arising from your use of the platform</li>
                <li>Do not warrant that the platform will be error-free or continuously available</li>
                <li>Reserve the right to modify or discontinue the platform at any time</li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-slate-800 mb-3">6. Private Beta Status</h2>
              <p className="text-sm leading-relaxed">
                Access to StockAnalyzer Pro is by private invite only. As a beta user, you agree to:
              </p>
              <ul className="list-disc list-inside mt-2 space-y-1 text-sm ml-4">
                <li>Use the platform only for research and educational purposes</li>
                <li>Provide feedback to help improve the platform</li>
                <li>Report any bugs or issues you encounter</li>
                <li>Understand that the platform may be unstable or unavailable at times</li>
              </ul>
            </section>

            <section className="pt-4 border-t border-slate-200">
              <p className="text-sm text-slate-600 italic">
                Last updated: {new Date().toLocaleDateString()}
              </p>
              <p className="text-sm text-slate-600 mt-2">
                If you have questions about this disclaimer, please contact us at{" "}
                <a
                  href="mailto:aaryanmanawat99@gmail.com"
                  className="text-emerald-600 hover:text-emerald-700 underline"
                >
                  aaryanmanawat99@gmail.com
                </a>
              </p>
            </section>
          </CardContent>
        </Card>
      </div>
    </div>
  );
};

export default Disclaimer;

