// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fjpxcnmogmspguftkvik.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZqcHhjbm1vZ21zcGd1ZnRrdmlrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxNTI1MDMsImV4cCI6MjA2NDcyODUwM30.KmuSs44GrfxKQdUI1iZzAneTU9mLFEa5XiHVFnGfvww";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);